repository=https://void.voidbr.org/voidlinux/current
repository=https://void.voidbr.org/voidlinux/extra
repository=https://void.voidbr.org/voidlinux/current/nonfree
repository=https://void.voidbr.org/voidlinux/current/multilib
repository=https://void.voidbr.org/voidlinux/current/multilib/nonfree
#
repository=https://void.chililinux.com/voidlinux/current
repository=https://void.chililinux.com/voidlinux/extra
#repository=https://void.chililinux.com/voidlinux/current/nonfree
#repository=https://void.chililinux.com/voidlinux/current/multilib
#repository=https://void.chililinux.com/voidlinux/current/multilib/nonfree

